### PR TITLE
Update to 2.34

### PR DESCRIPTION
**Pull request by jjhelmus**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Thanks for the PR and for volunteering to maintain.

**Comment by frol** [comment]
@jjhelmus Welcome aboard!

**Comment by jjhelmus** [comment]
The `linux-ppc64le` and `linux-aarch64` builds look to be failing when performing the downstream testing of gfortran and/or gcc.  It looks like `gfortran` on these platforms is pinning binutils down to the build number which conflicts with newly build package.

**Comment by isuruf** [comment]
@jjhelmus, isn't conda-build supposed to skip downstream testing if the new package can't be installed with the downstream package?

**Comment by jjhelmus** [comment]
> @jjhelmus, isn't conda-build supposed to skip downstream testing if the new package can't be installed with the downstream package?

Yes, those tests should have been skipped at least according to the [documentation](https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests):
> If conda-build can't create that environment due to unsatisfiable dependencies, it will skip those downstream tests and warn you

I've opened conda/conda-build#3908 for this issue.

**Pull request merged**
